name: cd-nuget
run-name: Deploy NuGet Package v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet Package Version'
        required: true
        default: '1.0.0'

jobs:
  cd:
    uses: hotfix-houdini/reusable-ci-cd/.github/workflows/reusable-dotnet-cd-nuget.yml@v1
    permissions:
      id-token: write 
      contents: write
      packages: read
    secrets: inherit
    with:
      SOLUTION_FILE_PATH: './BlockParty.sln'
      CSPROJ_PATH: 'src/BlockParty/BlockParty.csproj'
      DOTNET_VERSION: '8.0.x'
      NUGET_PACKAGE_VERSION: ${{ inputs.version }}
      PACKAGE_SOURCE: 'https://api.nuget.org/v3/index.json'
      RELEASE_NOTES_PATH: './latest-release-notes.md'