name: cd-nuget
run-name: Deploy NuGet Package v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet Package Version'
        required: true
        default: '1.0.0'

jobs:
  ci:
      uses: hotfix-houdini/reusable-ci-cd/.github/workflows/reusable-dotnet-ci.yml@main
      permissions:
        contents: read
        packages: read
      secrets: inherit
      with:
        BRANCH: ${{ inputs.BRANCH || github.ref }}
        SOLUTION_FILE_PATH: './BlockParty.sln'
        DOTNET_VERISON: '8.0.x'
  
  cd:
    uses: hotfix-houdini/reusable-ci-cd/.github/workflows/reusable-dotnet-cd-nuget.yml@main
    needs: [ci]
    permissions:
      id-token: write 
      contents: read
      packages: read
    secrets: inherit
    with:
      CSPROJ_PATH: 'src/BlockParty/BlockParty.csproj'
      DOTNET_VERSION: '8.0.x'
      NUGET_PACKAGE_VERSION: ${{ inputs.version }}
      PACKAGE_SOURCE: 'https://api.nuget.org/v3/index.json'
