name: ci-dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        BRANCH:
          description: 'Branch of source code'
          required: true
          default: 'main'
    
jobs:
  ci:
    uses: hotfix-houdini/reusable-ci-cd/.github/workflows/reusable-dotnet-ci.yml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit
    with:
      BRANCH: ${{ inputs.BRANCH || github.ref }}
      SOLUTION_FILE_PATH: './BlockParty.sln'
      DOTNET_VERISON: '8.0.x'